/*
 * This file is generated by jOOQ.
 */
package com.varit.backend.assessment.model.jooq;


import com.varit.backend.assessment.model.jooq.tables.Posts;
import com.varit.backend.assessment.model.jooq.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Backend extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>backend</code>
     */
    public static final Backend BACKEND = new Backend();

    /**
     * The table <code>backend.posts</code>.
     */
    public final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>backend.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Backend() {
        super("backend", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Posts.POSTS,
            Users.USERS
        );
    }
}
