/*
 * This file is generated by jOOQ.
 */
package com.varit.backend.assessment.model.jooq;


import com.varit.backend.assessment.model.jooq.tables.Posts;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in backend.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index POSTS_IDX_USER_ID = Internal.createIndex(DSL.name("idx_user_id"), Posts.POSTS, new OrderField[] { Posts.POSTS.USER_ID }, false);
}
