/*
 * This file is generated by jOOQ.
 */
package com.varit.backend.assessment.model.jooq;


import com.varit.backend.assessment.model.jooq.tables.Posts;
import com.varit.backend.assessment.model.jooq.tables.Users;


/**
 * Convenience access to all tables in backend.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>backend.posts</code>.
     */
    public static final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>backend.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
