/*
 * This file is generated by jOOQ.
 */
package com.varit.backend.assessment.model.jooq.tables.records;


import com.varit.backend.assessment.model.jooq.tables.Users;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record15<Integer, String, String, String, String, String, String, String, BigDecimal, BigDecimal, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>backend.users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>backend.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>backend.users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>backend.users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>backend.users.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>backend.users.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>backend.users.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>backend.users.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>backend.users.street</code>.
     */
    public void setStreet(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>backend.users.street</code>.
     */
    public String getStreet() {
        return (String) get(4);
    }

    /**
     * Setter for <code>backend.users.suite</code>.
     */
    public void setSuite(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>backend.users.suite</code>.
     */
    public String getSuite() {
        return (String) get(5);
    }

    /**
     * Setter for <code>backend.users.city</code>.
     */
    public void setCity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>backend.users.city</code>.
     */
    public String getCity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>backend.users.zipcode</code>.
     */
    public void setZipcode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>backend.users.zipcode</code>.
     */
    public String getZipcode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>backend.users.lat</code>.
     */
    public void setLat(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>backend.users.lat</code>.
     */
    public BigDecimal getLat() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>backend.users.lng</code>.
     */
    public void setLng(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>backend.users.lng</code>.
     */
    public BigDecimal getLng() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>backend.users.phone</code>.
     */
    public void setPhone(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>backend.users.phone</code>.
     */
    public String getPhone() {
        return (String) get(10);
    }

    /**
     * Setter for <code>backend.users.website</code>.
     */
    public void setWebsite(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>backend.users.website</code>.
     */
    public String getWebsite() {
        return (String) get(11);
    }

    /**
     * Setter for <code>backend.users.company_name</code>.
     */
    public void setCompanyName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>backend.users.company_name</code>.
     */
    public String getCompanyName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>backend.users.catch_phrase</code>.
     */
    public void setCatchPhrase(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>backend.users.catch_phrase</code>.
     */
    public String getCatchPhrase() {
        return (String) get(13);
    }

    /**
     * Setter for <code>backend.users.bs</code>.
     */
    public void setBs(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>backend.users.bs</code>.
     */
    public String getBs() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Integer, String, String, String, String, String, String, String, BigDecimal, BigDecimal, String, String, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Integer, String, String, String, String, String, String, String, BigDecimal, BigDecimal, String, String, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.USERNAME;
    }

    @Override
    public Field<String> field4() {
        return Users.USERS.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Users.USERS.STREET;
    }

    @Override
    public Field<String> field6() {
        return Users.USERS.SUITE;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.CITY;
    }

    @Override
    public Field<String> field8() {
        return Users.USERS.ZIPCODE;
    }

    @Override
    public Field<BigDecimal> field9() {
        return Users.USERS.LAT;
    }

    @Override
    public Field<BigDecimal> field10() {
        return Users.USERS.LNG;
    }

    @Override
    public Field<String> field11() {
        return Users.USERS.PHONE;
    }

    @Override
    public Field<String> field12() {
        return Users.USERS.WEBSITE;
    }

    @Override
    public Field<String> field13() {
        return Users.USERS.COMPANY_NAME;
    }

    @Override
    public Field<String> field14() {
        return Users.USERS.CATCH_PHRASE;
    }

    @Override
    public Field<String> field15() {
        return Users.USERS.BS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getUsername();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getStreet();
    }

    @Override
    public String component6() {
        return getSuite();
    }

    @Override
    public String component7() {
        return getCity();
    }

    @Override
    public String component8() {
        return getZipcode();
    }

    @Override
    public BigDecimal component9() {
        return getLat();
    }

    @Override
    public BigDecimal component10() {
        return getLng();
    }

    @Override
    public String component11() {
        return getPhone();
    }

    @Override
    public String component12() {
        return getWebsite();
    }

    @Override
    public String component13() {
        return getCompanyName();
    }

    @Override
    public String component14() {
        return getCatchPhrase();
    }

    @Override
    public String component15() {
        return getBs();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getUsername();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getStreet();
    }

    @Override
    public String value6() {
        return getSuite();
    }

    @Override
    public String value7() {
        return getCity();
    }

    @Override
    public String value8() {
        return getZipcode();
    }

    @Override
    public BigDecimal value9() {
        return getLat();
    }

    @Override
    public BigDecimal value10() {
        return getLng();
    }

    @Override
    public String value11() {
        return getPhone();
    }

    @Override
    public String value12() {
        return getWebsite();
    }

    @Override
    public String value13() {
        return getCompanyName();
    }

    @Override
    public String value14() {
        return getCatchPhrase();
    }

    @Override
    public String value15() {
        return getBs();
    }

    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UsersRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UsersRecord value5(String value) {
        setStreet(value);
        return this;
    }

    @Override
    public UsersRecord value6(String value) {
        setSuite(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setCity(value);
        return this;
    }

    @Override
    public UsersRecord value8(String value) {
        setZipcode(value);
        return this;
    }

    @Override
    public UsersRecord value9(BigDecimal value) {
        setLat(value);
        return this;
    }

    @Override
    public UsersRecord value10(BigDecimal value) {
        setLng(value);
        return this;
    }

    @Override
    public UsersRecord value11(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public UsersRecord value12(String value) {
        setWebsite(value);
        return this;
    }

    @Override
    public UsersRecord value13(String value) {
        setCompanyName(value);
        return this;
    }

    @Override
    public UsersRecord value14(String value) {
        setCatchPhrase(value);
        return this;
    }

    @Override
    public UsersRecord value15(String value) {
        setBs(value);
        return this;
    }

    @Override
    public UsersRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, BigDecimal value9, BigDecimal value10, String value11, String value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String name, String username, String email, String street, String suite, String city, String zipcode, BigDecimal lat, BigDecimal lng, String phone, String website, String companyName, String catchPhrase, String bs) {
        super(Users.USERS);

        setId(id);
        setName(name);
        setUsername(username);
        setEmail(email);
        setStreet(street);
        setSuite(suite);
        setCity(city);
        setZipcode(zipcode);
        setLat(lat);
        setLng(lng);
        setPhone(phone);
        setWebsite(website);
        setCompanyName(companyName);
        setCatchPhrase(catchPhrase);
        setBs(bs);
        resetChangedOnNotNull();
    }
}
